sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

language: java
install: true
jdk: oraclejdk8

env:
  matrix:
  - TERM=dumb

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd VUpdater-Core

before_script:
  - sh ./gradlew --version

script:
  - TERM=dumb ./gradlew build -S

after_success:
  - TERM=dumb ./gradlew test jacocoTestReport jacocoRootReport coveralls -S
