// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package eu.mihosoft.vrl.vupdater.proto;

public interface DeltaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.mihosoft.vrl.vupdater.proto.Delta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string from = 1;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>optional string from = 1;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>optional string to = 2;</code>
   */
  java.lang.String getTo();
  /**
   * <code>optional string to = 2;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>optional string path = 3;</code>
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 3;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional string asc = 4;</code>
   */
  java.lang.String getAsc();
  /**
   * <code>optional string asc = 4;</code>
   */
  com.google.protobuf.ByteString
      getAscBytes();

  /**
   * <code>optional string sha1 = 5;</code>
   */
  java.lang.String getSha1();
  /**
   * <code>optional string sha1 = 5;</code>
   */
  com.google.protobuf.ByteString
      getSha1Bytes();
}
