// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package eu.mihosoft.vrl.vupdater.proto;

public interface EntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.mihosoft.vrl.vupdater.proto.Entry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string desc = 2;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>optional string desc = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>optional string path = 3;</code>
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 3;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional string asc = 4;</code>
   */
  java.lang.String getAsc();
  /**
   * <code>optional string asc = 4;</code>
   */
  com.google.protobuf.ByteString
      getAscBytes();

  /**
   * <code>optional string sha1 = 5;</code>
   */
  java.lang.String getSha1();
  /**
   * <code>optional string sha1 = 5;</code>
   */
  com.google.protobuf.ByteString
      getSha1Bytes();
}
