// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package eu.mihosoft.vrl.vupdater.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_mihosoft_vrl_vupdater_proto_Entry_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_mihosoft_vrl_vupdater_proto_Entry_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_mihosoft_vrl_vupdater_proto_Delta_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_mihosoft_vrl_vupdater_proto_Delta_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_mihosoft_vrl_vupdater_proto_Repository_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_mihosoft_vrl_vupdater_proto_Repository_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\036eu.mihosoft.vrl.vupdate" +
      "r.proto\"J\n\005Entry\022\n\n\002id\030\001 \001(\t\022\014\n\004desc\030\002 \001" +
      "(\t\022\014\n\004path\030\003 \001(\t\022\013\n\003asc\030\004 \001(\t\022\014\n\004sha1\030\005 " +
      "\001(\t\"J\n\005Delta\022\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\014" +
      "\n\004path\030\003 \001(\t\022\013\n\003asc\030\004 \001(\t\022\014\n\004sha1\030\005 \001(\t\"" +
      "\206\001\n\nRepository\022\014\n\004desc\030\001 \001(\t\0224\n\005entry\030\002 " +
      "\003(\0132%.eu.mihosoft.vrl.vupdater.proto.Ent" +
      "ry\0224\n\005delta\030\003 \003(\0132%.eu.mihosoft.vrl.vupd" +
      "ater.proto.DeltaB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eu_mihosoft_vrl_vupdater_proto_Entry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_mihosoft_vrl_vupdater_proto_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_mihosoft_vrl_vupdater_proto_Entry_descriptor,
        new java.lang.String[] { "Id", "Desc", "Path", "Asc", "Sha1", });
    internal_static_eu_mihosoft_vrl_vupdater_proto_Delta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eu_mihosoft_vrl_vupdater_proto_Delta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_mihosoft_vrl_vupdater_proto_Delta_descriptor,
        new java.lang.String[] { "From", "To", "Path", "Asc", "Sha1", });
    internal_static_eu_mihosoft_vrl_vupdater_proto_Repository_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_eu_mihosoft_vrl_vupdater_proto_Repository_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_mihosoft_vrl_vupdater_proto_Repository_descriptor,
        new java.lang.String[] { "Desc", "Entry", "Delta", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
