// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package eu.mihosoft.vrl.vupdater.proto;

public interface RepositoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.mihosoft.vrl.vupdater.proto.Repository)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string desc = 1;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>optional string desc = 1;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>repeated .eu.mihosoft.vrl.vupdater.proto.Entry entry = 2;</code>
   */
  java.util.List<eu.mihosoft.vrl.vupdater.proto.Entry> 
      getEntryList();
  /**
   * <code>repeated .eu.mihosoft.vrl.vupdater.proto.Entry entry = 2;</code>
   */
  eu.mihosoft.vrl.vupdater.proto.Entry getEntry(int index);
  /**
   * <code>repeated .eu.mihosoft.vrl.vupdater.proto.Entry entry = 2;</code>
   */
  int getEntryCount();
  /**
   * <code>repeated .eu.mihosoft.vrl.vupdater.proto.Entry entry = 2;</code>
   */
  java.util.List<? extends eu.mihosoft.vrl.vupdater.proto.EntryOrBuilder> 
      getEntryOrBuilderList();
  /**
   * <code>repeated .eu.mihosoft.vrl.vupdater.proto.Entry entry = 2;</code>
   */
  eu.mihosoft.vrl.vupdater.proto.EntryOrBuilder getEntryOrBuilder(
      int index);

  /**
   * <code>repeated .eu.mihosoft.vrl.vupdater.proto.Delta delta = 3;</code>
   */
  java.util.List<eu.mihosoft.vrl.vupdater.proto.Delta> 
      getDeltaList();
  /**
   * <code>repeated .eu.mihosoft.vrl.vupdater.proto.Delta delta = 3;</code>
   */
  eu.mihosoft.vrl.vupdater.proto.Delta getDelta(int index);
  /**
   * <code>repeated .eu.mihosoft.vrl.vupdater.proto.Delta delta = 3;</code>
   */
  int getDeltaCount();
  /**
   * <code>repeated .eu.mihosoft.vrl.vupdater.proto.Delta delta = 3;</code>
   */
  java.util.List<? extends eu.mihosoft.vrl.vupdater.proto.DeltaOrBuilder> 
      getDeltaOrBuilderList();
  /**
   * <code>repeated .eu.mihosoft.vrl.vupdater.proto.Delta delta = 3;</code>
   */
  eu.mihosoft.vrl.vupdater.proto.DeltaOrBuilder getDeltaOrBuilder(
      int index);
}
